name: Push to dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Push dev branch to /var/www/html/curso-python/dev
        run: |
          rm -rf /var/www/html/curso-python/dev
          mkdir -p /var/www/html/curso-python/dev
          cp -r ./* /var/www/html/curso-python/dev
